# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://blaz.solar
title: "Blaž Šolar"
description: "Mobile Architect & Former CTO/Founder"
email: "hello@blaz.solar"
author: "Blaž Šolar"
description: "Mobile Architect & Former CTO/Founder"

header_pages: []

minima:
  skin: dark # Options: classic, dark, auto