# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://blaz.solar
title: Blaž Šolar
email: solarblaz@gmail.com
author: Blaž Šolar
description: "I'm head of Android development for Kamino d.o.o., a mobile development agency focused on producing high quality mobile apps. In this role I lead team of developers working on variety of Android project. My job, beside usual Android development is to stay ahead of the curve when it comes to producing high quality mobile apps. I try to scope out new technologies, come up with new ideas how to optimize development process and share that knowledge with coworkers.

Beside sharing my knowledge internally I also like to crate and contribute to open source project. One of the biggest is ButterProject/PopcornTime that allows user to stream video content to their preferred device. Other projects are anything from custom UI components for Android application to tools/plugins that make life for developers easy. Majority of them can be found at my Github account.

Alongside open source projects I also like to do public speaking on different types of events. In past few years I have had talks internally for coworkers, on local and international meetups/conferences and on Faculty of Computer and Information Science in Ljubljana. I also had a 16 lecture long class on introductory Android development in cooperation with SmartNija. 

Before Kamino, I was senior/lead Android developer at Fika, that was a startup focusing on making calendar experience nicer on mobile.

I’m always interested in hearing from former colleagues, potential clients, or just interesting creative folk, so feel free to contact me if you’d like to connect."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/solarb
  - title: github
    url: https://github.com/blazsolar
  - title: linkedin
    url: https://si.linkedin.com/pub/blaž-šolar/40/766/59a
